### ISSUE TITLE
Web API Service is not supported by the ServiceClient in 0.0 version of XRM.

### ISSUE THREAD

**Issue by pareszka** [microsoft/PowerPlatform-DataverseServiceClient#138]
From time to time my services are hitting this exception: 
System.InvalidOperationException: Web API Service is not supported by the ServiceClient in 0.0 version of XRM
   at Microsoft.PowerPlatform.Dataverse.Client.ServiceClient.CreateAsync(Entity entity, CancellationToken cancellationToken)

From what I checked in Dataverse's ServiceClient implementation, the _connectionSvc property is null there, and according to comment it's null when the call is done before organization is connected.
Not sure if this it the case, in most cases this path succeeds without any issues.
Can you help me understand if something else can cause this or maybe if there is a bug on your side related to this issue?

**Comment by MattB-msft** [comment]
Hi @pareszka could you provide a repro / example of what your doing, including how your creating the client and calling it?  that will help us understand where the issues is.

**Comment by pareszka** [comment]
The usage of ServiceClient is pretty standard, however I noticed that all occurrences of this bug happened when there was a heavy load on the organization (~8K Dataverse operations per minute), and in all cases it took over a minute from beginning of the request to getting this exception.
Probably this exception is a hidden timeout exception, and maybe some cleanup already happened before correct exception is thrown.
Our code is in internal MS repo, so you can ping me if you need more details.

**Comment by MattB-msft** [comment]
@pareszka the code that triggers this would be caused by a failure for dataverse to return instance information.  In a upcoming release we are refactoring how this works, however I would expect that its still going to persist as this would be caused by the remote failing. 

Were you seeing any other errors related to this?  if not, you should have seen a Request ID for the "get organization details" event,  that can be used to lookup in Dataverse what happened with it. 

And please do reach out to me internally so I can connect you with some internal folks to try to help.

**Comment by MattB-msft** [comment]
Closing as no response
