### ISSUE TITLE
.NET 5 assembly in package dependencies

### ISSUE THREAD

**Issue by drivardxrm** [microsoft/PowerPlatform-DataverseServiceClient#171]
I'm having issues using the package in an Azure Function project  (.Net Core 3.1)

It seems that there is a dependency on a .NET 5 assembly that was introduced since v0.5.2 (see image below)
**Microsoft.Extensions.Caching.Memory (>= 5.0.0)**

that itself depends on several other .NET 5 assemblies like 
**Microsoft.Extensions.Logging.Abstractions (>= 5.0.0)**

When I reference the latest version of the package, the Azure Function project compiles but triggers an error at startup.

System.Private.CoreLib: Could not load file or assembly '**Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0**, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')

It seems to be a known issue that happened with other packages : https://github.com/Azure/azure-functions-core-tools/issues/2304

As a workaround for the moment,  I need to revert back to v0.4.21. Then there are no issue and the function app runs smoothly.

Is there any chance that we can lower the version for this dependency to a .NET Core 3.1 compatible version.

Thanks

![image](https://user-images.githubusercontent.com/38399134/135938015-3010f140-fa33-4d83-8228-4f013cf65c29.png)

**Comment by MattB-msft** [comment]
Will check with the team,  I believed we had cleaned that up, bringing things to 3.18.

MattB
________________________________
From: David Rivard ***@***.***>
Sent: Monday, October 4, 2021 4:53:40 PM
To: microsoft/PowerPlatform-DataverseServiceClient ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/PowerPlatform-DataverseServiceClient] .NET 5 assembly in package dependencies (#171)


I'm having issues using the package in an Azure Function project (.Net Core 3.1)

It seems that there is a dependency on a .NET 5 assembly that was introduced since v0.5.2 (see image below)
Microsoft.Extensions.Caching.Memory (>= 5.0.0)

that itself depends on several other .NET 5 assemblies like
Microsoft.Extensions.Logging.Abstractions (>= 5.0.0)

When I reference the latest version of the package, the Azure Function project compiles but triggers an error at startup.

System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Value cannot be null. (Parameter 'provider')

It seems to be a known issue that happened with other packages : Azure/azure-functions-core-tools#2304<https://github.com/Azure/azure-functions-core-tools/issues/2304>

As a workaround for the moment, I need to revert back to v0.4.21. Then there are no issue and the function app runs smoothly.

Is there any chance that we can lower the version for this dependency to a .NET Core 3.1 compatible version.

Thanks

[image]<https://user-images.githubusercontent.com/38399134/135938015-3010f140-fa33-4d83-8228-4f013cf65c29.png>

**Comment by MattB-msft** [comment]
Team is fixing the external dependency and will have it posted later today,  
Internally its using Microsoft.Extensions.Caching.Memory.3.1.8,
