### ISSUE TITLE
Performance vs using HttpClient and WEB API 

### ISSUE THREAD

**Issue by petersk80** [microsoft/PowerPlatform-DataverseServiceClient#317]
Hi,

I would love if you could write a few sentences on performance using this SDK.

There seem to be a great majority that strongly believes this is just a wrapper that ends up using WEB API behind the scenes, and that using HttpClient and WebApi directly yield much better performance.

My belief is that the WEB API is also a wrapper and that if Microsoft releases an SDK (this one) they will strive to make most methods use the lowest level possible.

A few lines that makes this clear would be greatly appreciated.

**Comment by MattB-msft** [comment]
I believe I have covered this a few times from different angles and that should still be in the discussions area, and it's now covered on Microsoft Learn as well [here](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/webapi/overview).  

In answer to your specific questions though.  "Is this a wrapper on the webAPI" :
Yes and No :)   

The dataverse Service Client, fundamentally, exposes the "**Organization Service API**", Whereas the WebAPI exposes an **OData4 _approximation_** of the **Organization Service API**. 

The Dataverse system itself speaks Organization Service API.  Thus the webAPI is actually a wrapper on the Organization API that speaks the OData Protocol,  TSQL's interface is also quite similar, in that it is a wrapper on the Organization API. 

The Dataverse Service Client, when using the WS-* comm's channel, or a GRPC channel, is speaking Organization API natively.  When it talks to the WebAPI, its trying to do client-side translation of Organization API to WebAPI and back. 

We do not expose the protocol layer directly in the Dataverse ServiceClient because that allows us to change the protocol and transport technology to optimize for Organization Service Public access needs.   And do it in way that we do not break the consumers of the Organization Service API that the Dataverse ServiceClient exposes. 

All that said our API Client approach is this: 
When to use Odata 4:
If you want to control all aspects of your client, including Authentication, Code management, Policys for Retry and Network issues, data to object mapping and such and or you want to support a non .net supporting language.  OData 4 is for you. 

When to use the Dataverse ServiceClient:
if you're working with .net ( framework for .net core ), and you want to focus on the business logic you're writing, you're not interested in created or maintaining a communications client over the life of your application, you are willing to consume the logging interface provided, the authentication types we support (or extend them yourself if we do not support the particular method to get to a token you want to use), you are ok with the decisions the ServiceClient is going to make regarding retry, and throttling operations,  ServiceClient is for you. 

The ServiceClient is used by many of our internal services and we general integrated common patterns into the ServiceClient over time and make them public.  but it is an Opinionated Client, whereas the Odata API leaves it up to you to build your own client. 

Perf Wise, 
The Organization API is faster than the WebAPI (less serialization hops\metadata lookups), but we have optimized the systems across the board so that difference of "faster" is measured in sub-milliseconds when you're comparing the average request type where the ServiceClient is using the Organization Service Directly (that's the useWebAPI =false) vs Raw WebAPI.  Also not accounting for end client serialization costs that you would need to may for a WebAPI client.
