### ISSUE TITLE
OrganizationServiceContext does not have async support

### ISSUE THREAD

**Issue by shriyamal** [microsoft/PowerPlatform-DataverseServiceClient#363]
With the OrganizationServiceContext (which is also part of Microsoft.PowerPlatform.Dataverse.Client v1.0.26 package) it does not have async support (eg. it’s only possible to call SaveChanges, not for example SaveChangesAsync). Is this something your team are planning to support?

https://learn.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.client.organizationservicecontext?view=dataverse-sdk-latest

**Comment by MattB-msft** [comment]
Thanks for your feedback

Yes. this is known behavior.  
That class is used extensively on our server which does not have the IOrganizationServiceAsync Contract. 
We do not have plans to address this in the short to mid-term due to the current unavailability of the IOrganziationServiceAsync interface on the Dataverse server itself.
