### ISSUE TITLE
ServiceClient excessively acquires tokens when specifying AccessTokenProviderFunctionAsync and ExternalTokenManagement type

### ISSUE THREAD

**Issue by jimmy3912msncom** [microsoft/PowerPlatform-DataverseServiceClient#377]
We noticed in our logs after switching over to use the ServiceClient that for some reason it seems to excessively call to acquire an access token. It seems to call the AccessTokenProviderFunctionAsync once when instantiating the serviceClient, to acquire a token, then when you try to execute a request it seems to acquire access tokens again but this times 6 times for each request.

This means if we use the client to make:
1. 1 API call it will try to make 7 token request calls
2. 2 API calls it will try to make 13 token request calls
3. ...

Client details: Microsoft.PowerPlatform.Dataverse.Client Version=[1.0.39]
Target framework: .NET 6.0

We log each of our token requests and although it uses a cache it does add confusion to our service. Below is a sample of code that can be put together to reproduce this.

Also this is a gif of what I see:
![dvserviceclientexcesstokens](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/6807772/b17196b5-0e02-4a2c-86f9-217ba4249fbb)

```
...
        private int _authTokenAcquiryCount = 0;
        public async Task<string> GetTokenForInstanceAsync(Uri uri)
        {
            _authTokenAcquiryCount++;
            Console.WriteLine("coming in to acquire auth again " + uri);
            return "your token logic";
        }

        protected async Task AnalyzeAsync(bool withRecordingIngestion)
        {
            var targetUri = new Uri("orgUrl");
            var serviceClient = new PowerPlatform.Dataverse.Client.ServiceClient(
                new PowerPlatform.Dataverse.Client.Model.ConnectionOptions
                {
                    AccessTokenProviderFunctionAsync = _ => GetTokenForInstanceAsync(targetUri),
                    AuthenticationType = PowerPlatform.Dataverse.Client.AuthenticationType.ExternalTokenManagement,
                    ServiceUri = targetUri,
                    ClientId = "your client id",
                },
                false,
                new PowerPlatform.Dataverse.Client.Model.ConfigurationOptions()
                {
                    UseWebApi = true
                });

            await serviceClient.ExecuteAsync(new RetrieveMultipleRequest() { Query = new QueryExpression("usersettings") });

            await serviceClient.ExecuteAsync(new RetrieveMultipleRequest() { Query = new QueryExpression("usersettings") });

            await serviceClient.ExecuteAsync(new RetrieveMultipleRequest() { Query = new QueryExpression("usersettings") });
        }
...
```

**Comment by rajyraman** [comment]
Might be related to #161

**Comment by MattB-msft** [comment]
The service client acquires a new access token on each use of the internal IOrganziation service. (acquiring it for information for example).  In the onboard implementation, the service client handles the token access by determining the lifecycle of the token and returning it w/out asking MSAL for it. 
It does this because it knows the use case / scenario in play ( User Auth / or Client Cert | secret auth ) 

In the case of External authentication, the service client doesn't understand the scenario, thus token caching and returning of tokens is left entirely up to the external authentication handler. The reason that we don't make assumptions About the external authentication handler is that there exists scenarios where tokens need to be evaluated on a request by request basis. In such situations simply evaluating the token life cycle and returning the cached copy without sending the request to the external authentication handler, would create a situation where the client breaks the behavior required by the external authentication provider.  Should 'you' ( the external auth provider ) want to do it the same way that the Service Client does it, your welcome to copy the code we use to your provider.

**Comment by jimmy3912msncom** [comment]
Thank you for the explanation. I still think it would be good to document this for the client when using it so that this is not a surprise for users

**Comment by MattB-msft** [comment]
Thats fair,  we can discuss with docs team. 
Also we are going to push an update to reduce the number of times we ask for the token.
