### ISSUE TITLE
Utilities.ToExpandoObject() changes DateTime values of Entity

### ISSUE THREAD

**Issue by Demonofpower** [microsoft/PowerPlatform-DataverseServiceClient#404]
I get a Entity from the database and want to change some specific values of it.

![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/9366819/06bf8463-f4f1-4b2f-8ef6-b0788ad7af2c)

When I now change a value (I don´t even have to change a value it is enough to just call ServiceClient.Update(Entity)) something strange occurs.
![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/9366819/8559e245-4d2e-4e56-aab6-365e34c5d031)

My DateTime columns automatically get set 2 hours to the past. Eg. 12.12.2012 12:00 -> 12.12.2012 10:00 or even worse without time 12.12.2012 -> 11.12.2012 (I think because internally the time is 00:00)

I tried to find the cause of the problem and I was able to pin it down to the internal Utilities.ToExpandoObject() method.
When the entity is converted to the ExpandoObject the DateTime variables get changed.

![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/9366819/7ebbaf42-9634-4af9-b5c2-567ca855ced3)
![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/9366819/ef97eb97-6d50-4fee-9381-86d73dc0ef17)

Inside entity.Attributes:
![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/9366819/3f12f1d4-db1e-4741-bf65-081403b4be3f)

Inside rootExpando:
![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/9366819/c6d14029-b58e-4b7f-9f70-0a3f3ea83f96)

Is this a bug in the internal implementation or did I do somehing wrong?
Thank you very much

**Comment by Demonofpower** [comment]
I pinned down the problem even more and got to the point that the problematic conversion is [HERE](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/blob/447f9dc239f09d204e58c49598f04fe2de523b90/src/GeneralTools/DataverseClient/Client/Utils/Utils.cs#L584).
It converts the Entity DateTime entry which has a "Unspecified" Kind by default (after getting it from database with a QueryExpression) to UTC which sets the time 2 hours to the past.

Is this the intended behaviour? If so what should I do. Do I have to change the Kind of every Entity each time I get it from the database manually?

**Comment by MattB-msft** [comment]
This has been a sore spot for us for a while... 
the answer is "It depends" .
the API should be returning the base object for the date in UTC + offset.  However, if you have set up a localization profile for your user, that is not aways what the API does. 

This gets us in this client because we are doing Conversions off protocol to JSON and back for transit, so there is a 'best guess' going on as to what your (the clients) intentions actually are. 

That said,  if your using the current client versions, you should not be hitting this code path at all at this point. 
If you update to current, it maintains the original object and sends information to the OrgAPI as an DateTime natively.
