### ISSUE TITLE
_isCloning is not thread-safe in `SetClonedProperties`

### ISSUE THREAD

**Issue by clongfei** [microsoft/PowerPlatform-DataverseServiceClient#422]
I encountered an issue when I executed the **Clone()** function to clone a `ServiceClient` object. The getting `OrganizationDetail` action, which is supposed to be triggered during this process, inconsistently sends a request to Dataverse. I suspect this may be due to the **_isCloning** variable not being thread-safe. Based on my understanding, it shouldn't be necessary to send a request to Dataverse during a cloning operation.
 
![image](https://github.com/microsoft/PowerPlatform-DataverseServiceClient/assets/48342227/21ee042c-15b6-4fe7-906d-29bc08591be9)

**Comment by MattB-msft** [comment]
@clongfei  

Thanks for your report here. 
For this to trip up, it would mean that your trying to call clone from multiple threads concurrently. 
We will get this fixed.  However we strongly recommend you do not use clone here and instead use the Async versions of the calls to dataverse.

**Comment by FarmerenHE** [comment]
> However we strongly recommend you do not use clone here and instead use the Async versions of the calls to dataverse.
I think you should try to somehow make it more clear that .Clone() should only be used with .Net Framework and not with .Net Core when doing high workload.

When converting some old code to .Net Core we ran into a very high port usage, we traced it down to probably be related to our usage of clones (every call would use its own clone). After removing clones the issue seems to be resolved (waiting confirmation in production)

My guess (without having gone into details) is that the clones dont share their httpclients (it might be related to "require unique instances" being set to true on the serviceclient).
