### ISSUE TITLE
Dependency Check for 'WCF SERVICE <my>.crm.dynamics.com GET /XRMServices/2011/Organization.svc' Returns 401 Response Code

### ISSUE THREAD

**Issue by pros-iwaldman** [microsoft/PowerPlatform-DataverseServiceClient#460]
I encountered the following issue while using the Dataverse ServiceClient in an Azure Function App. The screenshot below, taken from Application Insights, illustrates this behavior:

![image](https://github.com/user-attachments/assets/106ae7ca-9ea3-480f-8d38-ce008733e134)

Do you have any insight into why the first call receives a 401 response code while subsequent calls are successful?

**Comment by MattB-msft** [comment]
This is by design. 
It's an http request that is being used to resolve the authority and resource for connecting to Power Platform. 

thanks.

**Comment by AngelNG83** [comment]
@MattB-msft 
Hello, I have the same issue in my project, and I'm not sure about this answer since we are making many service invocations, and in the end, we randomly get a connection error to Dataverse using Microsoft.PowerPlatform.Dataverse.Client. 

Could you please explain in detail how this works? Specifically, how the HTTP request resolves the authority and resource for connecting to Power Platform. Understanding the exact mechanism would help clarify the issue.

**Comment by ome-melo** [comment]
Hello @MattB-msft , 

Thank you for your work on this matter.

Me and my team are having the same issue in our project. We are making many service invocations and getting this log in our Application Insights instances, which is a bit misleading.
We have tried filtering it out but to no avail.

I join @AngelNG83 asking for further details.

Thanks!
